// <auto-generated />
namespace XMedicalLite_Windows.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modelo_triaje : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modelo_triaje));
        
        string IMigrationMetadata.Id
        {
            get { return "201912082312037_modelo_triaje"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
